/* OrbitBiz — clean invoice creator. */
(()=>{
  "use strict";
  const core=window.OrbitBiz=window.OrbitBiz||{},w=core.workspace=core.workspace||{};
  const esc=v=>w.esc(v),money=v=>w.money(v),today=()=>new Date().toISOString().slice(0,10);
  const line=(i,row={},items=[])=>`<div class="ob-invoice-line" data-invoice-line="${i}"><select name="item_id" data-item><option value="">Custom line</option>${items.map(x=>`<option value="${esc(x.id)}" ${row.item_id===x.id?"selected":""}>${esc(x.name)}${x.sku?` · ${esc(x.sku)}`:""}</option>`).join("")}</select><input name="description" data-description value="${esc(row.description||"")}" placeholder="Description" required><input name="quantity" data-quantity type="number" min="0.001" step="0.001" value="${row.quantity??1}" aria-label="Quantity"><input name="unit_price" data-price type="number" min="0" step="0.01" value="${row.unit_price??0}" aria-label="Unit price"><input name="discount" data-discount type="number" min="0" step="0.01" value="${row.discount??0}" aria-label="Discount"><input name="tax_rate" data-tax type="number" min="0" step="0.01" value="${row.tax_rate??0}" aria-label="Tax rate"><strong data-line-total>₹0</strong><button type="button" class="ob-line-remove" data-remove-line aria-label="Remove line">×</button></div>`;
  w.invoiceCreator=async(state,presetCustomerId="")=>{
    const db=w.db();if(!db||!state.businessId){w.toast("Workspace is not ready");return;}
    const [cr,ir]=await Promise.all([db.from("customers").select("id,name,company_name,gstin").eq("business_id",state.businessId).eq("is_active",true).order("name").limit(500),db.from("items").select("id,name,sku,selling_price,tax_rate,unit,item_type").eq("business_id",state.businessId).eq("is_active",true).order("name").limit(500)]);
    if(cr.error){w.toast("Could not load customers");return}if(ir.error){w.toast("Could not load catalogue");return}
    const customers=cr.data||[],items=ir.data||[],node=w.modal("New invoice",`<form class="ob-form ob-invoice-form" data-form="invoice"><div class="ob-invoice-head-grid"><label class="ob-field"><span>Customer</span><select name="customer_id" data-customer required><option value="">Select customer</option>${customers.map(c=>`<option value="${esc(c.id)}" ${presetCustomerId===c.id?"selected":""}>${esc(c.name)}${c.company_name?` · ${esc(c.company_name)}`:""}</option>`).join("")}</select></label>${w.field("Issue date","issue_date","date",true,today())}${w.field("Due date","due_date","date",false)}</div><div class="ob-invoice-lines-wrap"><div class="ob-invoice-lines-head"><span>ITEMS</span><button type="button" class="ob-soft" data-add-line>${w.icon("plus")} Add line</button></div><div class="ob-invoice-line labels"><span>Catalogue</span><span>Description</span><span>Qty</span><span>Rate</span><span>Discount</span><span>Tax %</span><span>Total</span><span></span></div><div data-invoice-lines>${line(0,{},items)}</div></div><div class="ob-invoice-footer"><div class="ob-invoice-notes">${w.textarea("Notes","notes","","Optional payment terms or notes")}</div><div class="ob-invoice-summary"><div><span>Subtotal</span><strong data-subtotal>₹0</strong></div><div><span>Discount</span><strong data-discount-total>₹0</strong></div><div><span>Tax</span><strong data-tax-total>₹0</strong></div><div class="grand"><span>Total</span><strong data-grand-total>₹0</strong></div></div></div><button class="ob-primary" type="submit">Create invoice ${w.icon("arrow")}</button></form>`);
    const form=node.querySelector("form"),lines=node.querySelector("[data-invoice-lines]"),recalc=()=>{let subtotal=0,discount=0,tax=0,total=0;lines.querySelectorAll("[data-invoice-line]").forEach(row=>{const q=Math.max(0,Number(row.querySelector("[data-quantity]").value||0)),p=Math.max(0,Number(row.querySelector("[data-price]").value||0)),d=Math.min(Math.max(0,Number(row.querySelector("[data-discount]").value||0)),q*p),r=Math.max(0,Number(row.querySelector("[data-tax]").value||0)),base=q*p,tx=(base-d)*r/100,lt=base-d+tx;subtotal+=base;discount+=d;tax+=tx;total+=lt;row.querySelector("[data-line-total]").textContent=money(lt)});node.querySelector("[data-subtotal]").textContent=money(subtotal);node.querySelector("[data-discount-total]").textContent=money(discount);node.querySelector("[data-tax-total]").textContent=money(tax);node.querySelector("[data-grand-total]").textContent=money(total)};
    const bind=row=>{row.querySelector("[data-item]").addEventListener("change",e=>{const item=items.find(x=>x.id===e.target.value);if(!item)return;row.querySelector("[data-description]").value=item.name;row.querySelector("[data-price]").value=Number(item.selling_price||0);row.querySelector("[data-tax]").value=Number(item.tax_rate||0);recalc()});row.querySelectorAll("input").forEach(x=>x.addEventListener("input",recalc));row.querySelector("[data-remove-line]").addEventListener("click",()=>{if(lines.children.length===1){w.toast("An invoice needs at least one line");return}row.remove();recalc()})};
    node.querySelector("[data-add-line]").addEventListener("click",()=>{lines.insertAdjacentHTML("beforeend",line(lines.children.length,{},items));bind(lines.lastElementChild);recalc()});bind(lines.firstElementChild);form.addEventListener("submit",e=>w.saveInvoice(e,state,node));recalc();
  };
  w.saveInvoice=async(event,state,node)=>{event.preventDefault();const form=event.currentTarget,rows=[...node.querySelectorAll("[data-invoice-line]")],raw=Object.fromEntries(new FormData(form).entries()),items=rows.map(row=>({item_id:row.querySelector("[data-item]").value||null,description:row.querySelector("[data-description]").value.trim(),quantity:Number(row.querySelector("[data-quantity]").value||0),unit_price:Number(row.querySelector("[data-price]").value||0),discount:Number(row.querySelector("[data-discount]").value||0),tax_rate:Number(row.querySelector("[data-tax]").value||0)}));if(!raw.customer_id){w.toast("Select a customer");return}if(items.some(x=>!x.description||x.quantity<=0||x.unit_price<0||x.discount<0||x.tax_rate<0)){w.toast("Check the invoice lines");return}const button=form.querySelector("button[type=submit]");button.disabled=true;button.textContent="Creating invoice…";try{const db=w.db(),result=await db.rpc("create_invoice_with_items",{p_business_id:state.businessId,p_customer_id:raw.customer_id,p_issue_date:raw.issue_date,p_due_date:raw.due_date||null,p_notes:raw.notes||null,p_items:items});if(result.error)throw result.error;node.remove();await state.renderPage();const created=await db.from("invoices").select("id").eq("business_id",state.businessId).eq("customer_id",raw.customer_id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(created.error)throw created.error;if(created.data?.id){state.openInvoice(created.data.id);setTimeout(async()=>{try{await w.prepareInvoicePdf(state,await w.invoiceDetailData(state,created.data.id))}catch(error){console.error(error);w.toast("Invoice created. PDF is available from the invoice page.")}},0)}else w.toast("Invoice created")}catch(error){console.error("Invoice creation failed",error);w.toast(error.message||"Could not create invoice");button.disabled=false;button.innerHTML=`Create invoice ${w.icon("arrow")}`}};
})();
