/* OrbitBiz — invoice creator. */
(()=>{
  "use strict";
  const core=window.OrbitBiz=window.OrbitBiz||{},w=core.workspace=core.workspace||{};
  const esc=v=>w.esc(v),money=v=>w.money(v),today=()=>new Date().toISOString().slice(0,10);
  const picker=(type,list,selected="")=>{const id=`ob-${type}-search-${Math.random().toString(36).slice(2,9)}`,isCustomer=type==="customer",chosen=list.find(x=>x.id===selected),chosenLabel=chosen?(isCustomer?`${chosen.name}${chosen.company_name?` · ${chosen.company_name}`:""}`:`${chosen.name}${chosen.sku?` · ${chosen.sku}`:""}`):"";return `<div class="ob-search-picker" data-picker="${type}"><div class="ob-search-row"><input type="text" list="${id}" data-picker-input value="${esc(chosenLabel)}" placeholder="Search ${isCustomer?"customer":"product"}…" autocomplete="off"><button type="button" class="ob-soft ob-picker-add" data-add-now>${w.icon("plus")} Add now</button></div><input type="hidden" data-picker-id value="${esc(selected)}"><datalist id="${id}">${list.map(x=>{const label=isCustomer?`${x.name}${x.company_name?` · ${x.company_name}`:""}`:`${x.name}${x.sku?` · ${x.sku}`:""}`;return `<option value="${esc(label)}" data-id="${esc(x.id)}"></option>`}).join("")}</datalist><small class="ob-picker-hint" data-picker-hint>${chosen?(isCustomer?"Customer selected.":"Product selected."):"Search and choose from your " +(isCustomer?"customers":"catalogue")+"."}</small></div>`};
  const line=(i,row={},items=[])=>`<div class="ob-invoice-line" data-invoice-line="${i}"><div data-item-picker>${picker("item",items,row.item_id||"")}</div><input name="description" data-description value="${esc(row.description||"")}" placeholder="Description" required><input name="quantity" data-quantity type="number" min="0.001" step="0.001" value="${row.quantity??1}" aria-label="Quantity"><input name="unit_price" data-price type="number" min="0" step="0.01" value="${row.unit_price??0}" aria-label="Unit price"><input name="discount" data-discount type="number" min="0" step="0.01" value="${row.discount??0}" aria-label="Discount"><input name="tax_rate" data-tax type="number" min="0" step="0.01" value="${row.tax_rate??0}" aria-label="Tax rate"><strong data-line-total>₹0</strong><button type="button" class="ob-line-remove" data-remove-line aria-label="Remove line">×</button></div>`;
  const wirePicker=(root,type,list,onPick,onAdd)=>{const input=root.querySelector("[data-picker-input]"),hidden=root.querySelector("[data-picker-id]"),hint=root.querySelector("[data-picker-hint]"),isCustomer=type==="customer";const resolve=()=>{const value=input.value.trim().toLowerCase(),found=list.find(x=>{const label=isCustomer?`${x.name}${x.company_name?` · ${x.company_name}`:""}`:`${x.name}${x.sku?` · ${x.sku}`:""}`;return label.toLowerCase()===value||String(x.id)===value});hidden.value=found?.id||"";hint.textContent=found?(isCustomer?"Customer selected.":"Product selected."):(value?`No exact match. Use “Add now” to create this ${isCustomer?"customer":"product"}.`:`Search and choose from your ${isCustomer?"customers":"catalogue"}.`);if(found)onPick?.(found)};input.addEventListener("input",resolve);input.addEventListener("change",resolve);root.querySelector("[data-add-now]").addEventListener("click",()=>onAdd?.(input.value.trim()));return{input,hidden}};
  const inlineCreate=(node,state,type,seed,onSaved)=>{const isCustomer=type==="customer";const wrap=document.createElement("div");wrap.className="ob-picker-create";wrap.innerHTML=`<div class="ob-picker-create-head"><strong>Add ${isCustomer?"customer":"product"}</strong><button type="button" data-cancel>×</button></div><form class="ob-form"><div class="ob-form-grid">${w.field("Name","name","text",true,seed)}${isCustomer?w.field("Company","company_name"):w.field("SKU","sku")}${isCustomer?w.field("Phone","phone","tel"):w.field("Sale price","selling_price","number")}${isCustomer?w.field("GSTIN","gstin"):w.field("Tax rate","tax_rate","number")}</div><button class="ob-primary small" type="submit">Save ${isCustomer?"customer":"product"}</button></form>`;node.querySelector(".ob-modal-card")?.appendChild(wrap);wrap.querySelector("[data-cancel]").onclick=()=>wrap.remove();wrap.querySelector("form").addEventListener("submit",async e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget).entries()),name=String(raw.name||"").trim();if(!name){w.toast("Name is required");return}const data=isCustomer?{business_id:state.businessId,name,company_name:String(raw.company_name||"").trim()||null,phone:String(raw.phone||"").trim()||null,gstin:String(raw.gstin||"").trim()||null}:{business_id:state.businessId,name,sku:String(raw.sku||"").trim()||null,selling_price:Number(raw.selling_price||0),tax_rate:Number(raw.tax_rate||0),is_active:true};const result=await w.db().from(isCustomer?"customers":"items").insert(data).select(isCustomer?"id,name,company_name,gstin":"id,name,sku,selling_price,tax_rate,unit,item_type").single();if(result.error){w.toast(result.error.message||`Could not add ${isCustomer?"customer":"product"}`);return}wrap.remove();w.toast(`${isCustomer?"Customer":"Product"} added`);onSaved?.(result.data)})};
  w.invoiceCreator=async(state,presetCustomerId="")=>{
    const db=w.db();if(!db||!state.businessId){w.toast("Workspace is not ready");return}
    const [cr,ir]=await Promise.all([db.from("customers").select("id,name,company_name,gstin").eq("business_id",state.businessId).eq("is_active",true).order("name").limit(500),db.from("items").select("id,name,sku,selling_price,tax_rate,unit,item_type").eq("business_id",state.businessId).eq("is_active",true).order("name").limit(500)]);
    if(cr.error){w.toast(cr.error.message||"Could not load customers");return}if(ir.error){w.toast(ir.error.message||"Could not load catalogue");return}
    let customers=cr.data||[],items=ir.data||[];
    const node=w.modal("New invoice",`<form class="ob-form ob-invoice-form" data-form="invoice"><div class="ob-invoice-head-grid"><label class="ob-field"><span>Customer</span><div data-customer-picker>${picker("customer",customers,presetCustomerId)}</div></label>${w.field("Issue date","issue_date","date",true,today())}${w.field("Due date","due_date","date",false)}</div><div class="ob-invoice-lines-wrap"><div class="ob-invoice-lines-head"><span>ITEMS</span><button type="button" class="ob-soft" data-add-line>${w.icon("plus")} Add line</button></div><div class="ob-invoice-line labels"><span>Product search</span><span>Description</span><span>Qty</span><span>Rate</span><span>Discount</span><span>Tax %</span><span>Total</span><span></span></div><div data-invoice-lines>${line(0,{},items)}</div></div><div class="ob-invoice-footer"><div class="ob-invoice-notes">${w.textarea("Notes","notes","","Optional payment terms or notes")}</div><div class="ob-invoice-summary"><div><span>Subtotal</span><strong data-subtotal>₹0</strong></div><div><span>Discount</span><strong data-discount-total>₹0</strong></div><div><span>Tax</span><strong data-tax-total>₹0</strong></div><div class="grand"><span>Total</span><strong data-grand-total>₹0</strong></div></div></div><button class="ob-primary" type="submit">Create invoice ${w.icon("arrow")}</button></form>`);
    const form=node.querySelector("form"),lines=node.querySelector("[data-invoice-lines]"),recalc=()=>{let subtotal=0,discount=0,tax=0,total=0;lines.querySelectorAll("[data-invoice-line]").forEach(row=>{const q=Math.max(0,Number(row.querySelector("[data-quantity]").value||0)),p=Math.max(0,Number(row.querySelector("[data-price]").value||0)),d=Math.min(Math.max(0,Number(row.querySelector("[data-discount]").value||0)),q*p),r=Math.max(0,Number(row.querySelector("[data-tax]").value||0)),base=q*p,tx=(base-d)*r/100,lt=base-d+tx;subtotal+=base;discount+=d;tax+=tx;total+=lt;row.querySelector("[data-line-total]").textContent=money(lt)});node.querySelector("[data-subtotal]").textContent=money(subtotal);node.querySelector("[data-discount-total]").textContent=money(discount);node.querySelector("[data-tax-total]").textContent=money(tax);node.querySelector("[data-grand-total]").textContent=money(total)};
    const bindPicker=(root,type,list,onPick)=>wirePicker(root,type,list,onPick,seed=>inlineCreate(node,state,type,seed,newRow=>{list.push(newRow);const input=root.querySelector("[data-picker-input]"),hidden=root.querySelector("[data-picker-id]");const label=type==="customer"?`${newRow.name}${newRow.company_name?` · ${newRow.company_name}`:""}`:`${newRow.name}${newRow.sku?` · ${newRow.sku}`:""}`;input.value=label;hidden.value=newRow.id;root.querySelector("[data-picker-hint]").textContent=type==="customer"?"Customer added and selected.":"Product added and selected.";onPick?.(newRow)}));
    bindPicker(node.querySelector("[data-customer-picker]"),"customer",customers);
    const bind=row=>{bindPicker(row.querySelector("[data-item-picker]"),"item",items,item=>{row.querySelector("[data-description]").value=item.name;row.querySelector("[data-price]").value=Number(item.selling_price||0);row.querySelector("[data-tax]").value=Number(item.tax_rate||0);recalc()});row.querySelectorAll("input").forEach(x=>x.addEventListener("input",recalc));row.querySelector("[data-remove-line]").addEventListener("click",()=>{if(lines.children.length===1){w.toast("An invoice needs at least one line");return}row.remove();recalc()})};
    node.querySelector("[data-add-line]").addEventListener("click",()=>{lines.insertAdjacentHTML("beforeend",line(lines.children.length,{},items));bind(lines.lastElementChild);recalc()});bind(lines.firstElementChild);form.addEventListener("submit",e=>w.saveInvoice(e,state,node));recalc();
  };
  w.saveInvoice=async(event,state,node)=>{
    event.preventDefault();
    const form=event.currentTarget,rows=[...node.querySelectorAll("[data-invoice-line]")],raw=Object.fromEntries(new FormData(form).entries()),items=rows.map(row=>({item_id:row.querySelector("[data-picker-id]").value||null,description:row.querySelector("[data-description]").value.trim(),quantity:Number(row.querySelector("[data-quantity]").value||0),unit_price:Number(row.querySelector("[data-price]").value||0),discount:Number(row.querySelector("[data-discount]").value||0),tax_rate:Number(row.querySelector("[data-tax]").value||0)}));
    const customerId=node.querySelector("[data-customer-picker] [data-picker-id]")?.value||"";
    if(!customerId){w.toast("Search and select a customer, or use Add now");return}if(items.some(x=>!x.description||x.quantity<=0||x.unit_price<0||x.discount<0||x.tax_rate<0)){w.toast("Check the invoice lines");return}
    const button=form.querySelector("button[type=submit]"),db=w.db();button.disabled=true;button.textContent="Creating invoice…";
    try{const result=await db.rpc("create_invoice_with_items",{p_business_id:state.businessId,p_customer_id:customerId,p_issue_date:raw.issue_date,p_due_date:raw.due_date||null,p_notes:raw.notes||null,p_items:items});if(result.error)throw result.error;const invoiceId=result.data;if(!invoiceId)throw Error("Invoice was created but its ID was not returned");node.remove();w.toast("Invoice created");const detail=await w.invoiceDetailData(state,invoiceId);if(typeof w.prepareInvoicePdf!=="function")throw Error("PDF engine is not available");await w.prepareInvoicePdf(state,detail);state.page="invoices";state.invoiceId=invoiceId;state.invoiceCustomerId="";state._openNewInvoice=false;await state.renderPage()}catch(error){console.error("Invoice creation/PDF flow failed",error);w.toast(error.message||"Could not finish invoice creation");button.disabled=false;button.innerHTML=`Create invoice ${w.icon("arrow")}`}
  };
})();
