/* OrbitBiz workspace — connected finance, purchasing and reporting views. */
(() => {
  "use strict";
  const core = window.OrbitBiz = window.OrbitBiz || {};
  const w = core.workspace = core.workspace || {};
  const esc = v => w.esc(v);
  const money = v => w.money(v);
  const today = () => new Date().toISOString().slice(0,10);
  const rows = async (state, table, columns="*") => w.safe(state, table, columns);
  const card = (title, value, note, tone="yellow") => `<article class="ob-op-card ${tone}"><span>${esc(title)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></article>`;
  const status = value => `<span class="ob-status ${String(value||"").toLowerCase()==="paid"||String(value||"").toLowerCase()==="completed" ? "done" : "open"">${esc(value || "Open")}</span>`;

  w.financeView = async state => {
    const [payments, expenses, accounts] = await Promise.all([
      rows(state,"payments","id,amount,payment_date,method,reference,created_at"),
      rows(state,"expenses","id,expense_date,category,description,amount,tax_amount,payment_method,reference,created_at"),
      rows(state,"payment_accounts","id,name,account_type,opening_balance,current_balance,is_active")
    ]);
    const received = payments.reduce((s,r)=>s+Number(r.amount||0),0);
    const spent = expenses.reduce((s,r)=>s+Number(r.amount||0),0);
    const balance = accounts.reduce((s,r)=>s+Number(r.current_balance ?? r.opening_balance ?? 0),0);
    return `<div class="ob-op-hero"><div><span class="ob-eyebrow">MONEY CONTROL</span><h2>Know where the money is.</h2><p>Track incoming payments, outgoing expenses and payment accounts from one view.</p></div><button class="ob-primary" data-action="new-expense">${w.icon("plus")} Record expense</button></div>
      <section class="ob-op-metrics">${card("Money received",money(received),`${payments.length} recorded payment${payments.length===1?"":"s"}`,"green")}${card("Expenses",money(spent),`${expenses.length} recorded expense${expenses.length===1?"":"s"}`,"pink")}${card("Account balance",money(balance),`${accounts.length} payment account${accounts.length===1?"":"s"}`,"blue")}</section>
      <section class="ob-op-grid"><article class="ob-panel"><div class="ob-panel-head"><div><span>PAYMENT ACCOUNTS</span><h3>Your money</h3></div></div>${accounts.length?`<div class="ob-account-list">${accounts.map(a=>`<div class="ob-account"><div class="ob-account-icon">${w.icon("finance")}</div><div><strong>${esc(a.name)}</strong><small>${esc(a.account_type||"Account")}</small></div><b>${money(a.current_balance ?? a.opening_balance)}</b></div>`).join("")}</div>`:`<div class="ob-empty compact"><div>${w.icon("finance")}</div><h4>No payment accounts</h4><p>Add a bank or cash account in Settings when account management is enabled.</p></div>`}</article>
      <article class="ob-panel"><div class="ob-panel-head"><div><span>RECENT PAYMENTS</span><h3>Money in</h3></div></div>${payments.length?`<div class="ob-op-list">${payments.slice(0,7).map(r=>`<div><span>${esc(r.payment_date||r.created_at||"—")}</span><strong>${money(r.amount)}</strong><small>${esc(r.method||"Payment")}${r.reference?` · ${esc(r.reference)}`:""}</small></div>`).join("")}</div>`:`<div class="ob-empty compact"><div>${w.icon("finance")}</div><h4>No payments yet</h4><p>Customer payments will appear here as you record them.</p></div>`}</article></section>
      <article class="ob-panel ob-full-panel"><div class="ob-panel-head"><div><span>EXPENSES</span><h3>Recent spending</h3></div><button class="ob-primary small" data-action="new-expense">${w.icon("plus")} Add expense</button></div>${expenses.length?`<div class="ob-table-scroll"><table class="ob-table"><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Method</th><th>Amount</th></tr></thead><tbody>${expenses.slice(0,30).map(r=>`<tr><td>${esc(r.expense_date||"—")}</td><td>${esc(r.category||"General")}</td><td>${esc(r.description||"—")}</td><td>${esc(r.payment_method||"—")}</td><td><strong>${money(r.amount)}</strong></td></tr>`).join("")}</tbody></table></div>`:`<div class="ob-empty"><div>${w.icon("finance")}</div><h4>No expenses recorded</h4><p>Keep operating costs here so reports can reflect real business movement.</p><button class="ob-soft" data-action="new-expense">${w.icon("plus")} Record first expense</button></div>`}</article>`;
  };

  w.newExpense = state => {
    const node = w.modal("Record expense", `<form class="ob-form" data-form="expense"><div class="ob-form-grid">${w.field("Date","expense_date","date",true,today())}${w.field("Category","category","text",true,"","e.g. Rent, utilities, travel")}${w.field("Amount","amount","number",true,"", "0.00")}${w.field("Tax amount","tax_amount","number",false,"0","0.00")}${w.field("Payment method","payment_method","text",false,"","Cash, bank, UPI…")}${w.field("Reference","reference")}</div>${w.textarea("Description","description","","What was this expense for?")}<button class="ob-primary" type="submit">Save expense ${w.icon("arrow")}</button></form>`);
    node.querySelector("form")?.addEventListener("submit",e=>w.saveExpense(e,state));
  };
  w.saveExpense = async (event,state) => {
    event.preventDefault(); const form=event.currentTarget; const raw=Object.fromEntries(new FormData(form).entries());
    const amount=Number(raw.amount||0), tax=Number(raw.tax_amount||0);
    if(!raw.category?.trim() || !Number.isFinite(amount) || amount<=0 || !Number.isFinite(tax) || tax<0){w.toast("Enter a valid category and amount");return;}
    const result=await w.db().from("expenses").insert({business_id:state.businessId,expense_date:raw.expense_date||today(),category:raw.category.trim(),description:raw.description?.trim()||null,amount,tax_amount:tax,payment_method:raw.payment_method?.trim()||null,reference:raw.reference?.trim()||null});
    if(result.error){w.toast(result.error.message||"Could not save expense");return;} form.closest(".ob-modal")?.remove(); w.toast("Expense recorded"); await state.renderPage();
  };

  w.purchasesView = async state => {
    const purchases=await rows(state,"purchases","id,purchase_number,vendor_id,purchase_date,status,subtotal,tax_total,total,notes,created_at");
    const vendors=await rows(state,"vendors","id,name,company_name"); const vm=new Map(vendors.map(v=>[v.id,v.company_name||v.name]));
    const total=purchases.reduce((s,r)=>s+Number(r.total||0),0);
    return `<div class="ob-op-hero"><div><span class="ob-eyebrow">BUY & STOCK</span><h2>Purchases, connected.</h2><p>Record supplier purchases with real totals and keep the buying side of the business organised.</p></div><button class="ob-primary" data-action="new-purchase">${w.icon("plus")} New purchase</button></div><section class="ob-op-metrics">${card("Purchases",money(total),`${purchases.length} document${purchases.length===1?"":"s"}`,"yellow")}${card("Suppliers",String(vendors.length),"Available vendor records","blue")}${card("Average",money(purchases.length?total/purchases.length:0),"Per purchase document","green")}</section><article class="ob-panel ob-full-panel"><div class="ob-panel-head"><div><span>PURCHASE REGISTER</span><h3>Supplier purchases</h3></div><button class="ob-primary small" data-action="new-purchase">${w.icon("plus")} Add purchase</button></div>${purchases.length?`<div class="ob-table-scroll"><table class="ob-table"><thead><tr><th>Purchase</th><th>Supplier</th><th>Date</th><th>Status</th><th>Subtotal</th><th>Total</th></tr></thead><tbody>${purchases.map(r=>`<tr><td><strong>${esc(r.purchase_number||"Purchase")}</strong></td><td>${esc(vm.get(r.vendor_id)||"Unknown supplier")}</td><td>${esc(r.purchase_date||"—")}</td><td>${status(r.status)}</td><td>${money(r.subtotal)}</td><td><strong>${money(r.total)}</strong></td></tr>`).join("")}</tbody></table></div>`:`<div class="ob-empty"><div>${w.icon("purchases")}</div><h4>No purchases yet</h4><p>Record your first supplier purchase to connect buying with inventory.</p><button class="ob-soft" data-action="new-purchase">${w.icon("plus")} Record purchase</button></div>`}</article>`;
  };

  w.newPurchase = async state => {
    const [vendors,items]=await Promise.all([rows(state,"vendors","id,name,company_name"),rows(state,"items","id,name,sku,purchase_price,selling_price,tax_rate")]);
    const line=()=>`<div class="ob-purchase-line" data-purchase-line><select data-item><option value="">Select item</option>${items.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}${x.sku?` · ${esc(x.sku)}`:""}</option>`).join("")}</select><input data-description placeholder="Description" required><input data-qty type="number" min="0.001" step="0.001" value="1"><input data-price type="number" min="0" step="0.01" value="0"><input data-tax type="number" min="0" step="0.01" value="0"><strong data-total>₹0</strong><button type="button" data-remove-line>×</button></div>`;
    const node=w.modal("New purchase",`<form class="ob-form ob-purchase-form"><div class="ob-form-grid"><label class="ob-field"><span>Supplier</span><select name="vendor_id" required><option value="">Select supplier</option>${vendors.map(v=>`<option value="${esc(v.id)}">${esc(v.company_name||v.name)}</option>`).join("")}</select></label>${w.field("Purchase date","purchase_date","date",true,today())}</div><div class="ob-invoice-lines-wrap"><div class="ob-invoice-lines-head"><span>ITEMS</span><button type="button" class="ob-soft" data-add-purchase-line>${w.icon("plus")} Add line</button></div><div class="ob-purchase-line labels"><span>Item</span><span>Description</span><span>Qty</span><span>Rate</span><span>Tax %</span><span>Total</span><span></span></div><div data-purchase-lines>${line()}</div></div>${w.textarea("Notes","notes","","Optional purchase notes")}<div class="ob-purchase-summary"><span>Total</span><strong data-purchase-grand>₹0</strong></div><button class="ob-primary" type="submit">Save purchase ${w.icon("arrow")}</button></form>`);
    const form=node.querySelector("form"), container=node.querySelector("[data-purchase-lines]");
    const recalc=()=>{let total=0;container.querySelectorAll("[data-purchase-line]").forEach(r=>{const q=Math.max(0,Number(r.querySelector("[data-qty]").value||0)),p=Math.max(0,Number(r.querySelector("[data-price]").value||0)),t=Math.max(0,Number(r.querySelector("[data-tax]").value||0));const lt=q*p*(1+t/100);total+=lt;r.querySelector("[data-total]").textContent=money(lt);});node.querySelector("[data-purchase-grand]").textContent=money(total);};
    const bind=row=>{row.querySelector("[data-item]").addEventListener("change",e=>{const x=items.find(i=>i.id===e.target.value);if(x){row.querySelector("[data-description]").value=x.name;row.querySelector("[data-price]").value=Number(x.purchase_price??x.selling_price??0);row.querySelector("[data-tax]").value=Number(x.tax_rate||0);recalc();}});row.querySelectorAll("input").forEach(i=>i.addEventListener("input",recalc));row.querySelector("[data-remove-line]").addEventListener("click",()=>{if(container.children.length>1){row.remove();recalc();}else w.toast("A purchase needs at least one line");});};
    bind(container.firstElementChild); node.querySelector("[data-add-purchase-line]").addEventListener("click",()=>{container.insertAdjacentHTML("beforeend",line());bind(container.lastElementChild);recalc();});
    form.addEventListener("submit",async e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(form).entries());const lines=[...container.querySelectorAll("[data-purchase-line]")].map(r=>({item_id:r.querySelector("[data-item]").value||null,description:r.querySelector("[data-description]").value.trim(),quantity:Number(r.querySelector("[data-qty]").value||0),unit_price:Number(r.querySelector("[data-price]").value||0),tax_rate:Number(r.querySelector("[data-tax]").value||0)}));if(!raw.vendor_id||lines.some(x=>!x.description||x.quantity<=0||x.unit_price<0||x.tax_rate<0)){w.toast("Complete the supplier and purchase lines");return;}const subtotal=lines.reduce((s,x)=>s+x.quantity*x.unit_price,0),tax_total=lines.reduce((s,x)=>s+x.quantity*x.unit_price*x.tax_rate/100,0),total=subtotal+tax_total;const purchaseNumber=`PUR-${Date.now().toString().slice(-8)}`;const pr=await w.db().from("purchases").insert({business_id:state.businessId,vendor_id:raw.vendor_id,purchase_number:purchaseNumber,purchase_date:raw.purchase_date||today(),status:"draft",subtotal,tax_total,total,notes:raw.notes?.trim()||null}).select("id").single();if(pr.error){w.toast(pr.error.message||"Could not save purchase");return;}const ir=await w.db().from("purchase_items").insert(lines.map(x=>({...x,purchase_id:pr.data.id,line_total:x.quantity*x.unit_price*(1+x.tax_rate/100)})));if(ir.error){w.toast(ir.error.message||"Purchase header saved but lines failed");return;}node.remove();w.toast("Purchase saved");await state.renderPage();});recalc();
  };

  w.reportsView = async state => {
    const [invoices,payments,expenses,purchases,customers,items]=await Promise.all([rows(state,"invoices","id,total,amount_paid,status,issue_date,created_at"),rows(state,"payments","id,amount,payment_date,created_at"),rows(state,"expenses","id,amount,tax_amount,expense_date,category"),rows(state,"purchases","id,total,purchase_date,status"),rows(state,"customers","id,created_at"),rows(state,"items","id,opening_stock,selling_price")]);
    const sales=invoices.reduce((s,r)=>s+Number(r.total||0),0),received=payments.reduce((s,r)=>s+Number(r.amount||0),0),spent=expenses.reduce((s,r)=>s+Number(r.amount||0),0),bought=purchases.reduce((s,r)=>s+Number(r.total||0),0),outstanding=Math.max(0,sales-invoices.reduce((s,r)=>s+Number(r.amount_paid||0),0));
    const margin=sales-spent-bought;
    const byCat={};expenses.forEach(r=>{const k=r.category||"General";byCat[k]=(byCat[k]||0)+Number(r.amount||0);});
    const topCats=Object.entries(byCat).sort((a,b)=>b[1]-a[1]).slice(0,6);
    return `<div class="ob-op-hero"><div><span class="ob-eyebrow">BUSINESS INTELLIGENCE</span><h2>Numbers that explain the business.</h2><p>A live snapshot built from your real records — no demo figures.</p></div></div><section class="ob-op-metrics">${card("Sales",money(sales),`${invoices.length} invoice${invoices.length===1?"":"s"}`,"yellow")}${card("Received",money(received),`${payments.length} payment${payments.length===1?"":"s"}`,"green")}${card("Outstanding",money(outstanding),"Customer receivables","blue")}${card("Net movement",money(margin),"Sales less purchases and expenses","pink")}</section><section class="ob-op-grid"><article class="ob-panel"><div class="ob-panel-head"><div><span>EXPENSE MIX</span><h3>Where money goes</h3></div></div>${topCats.length?`<div class="ob-report-bars">${topCats.map(([k,v])=>`<div class="ob-report-bar"><div><span>${esc(k)}</span><b>${money(v)}</b></div><div class="ob-report-track"><i style="width:${Math.min(100,spent?Math.max(2,v/spent*100):0)}%"></i></div></div>`).join("")}</div>`:`<div class="ob-empty compact"><div>${w.icon("reports")}</div><h4>No expense data</h4><p>Expense categories will appear as you record costs.</p></div>`}</article><article class="ob-panel"><div class="ob-panel-head"><div><span>OPERATING COUNTS</span><h3>Business activity</h3></div></div><div class="ob-op-list"><div><span>Customers</span><strong>${customers.length}</strong><small>Directory records</small></div><div><span>Catalogue items</span><strong>${items.length}</strong><small>Products and services</small></div><div><span>Purchases</span><strong>${purchases.length}</strong><small>Supplier documents</small></div><div><span>Invoices</span><strong>${invoices.length}</strong><small>Sales documents</small></div></div></article></section>`;
  };
})();