/* OrbitBiz workspace — connected finance, purchasing and reporting views. */
(() => {
  "use strict";
  const core = window.OrbitBiz = window.OrbitBiz || {};
  const w = core.workspace = core.workspace || {};
  const esc = v => w.esc(v);
  const money = v => w.money(v);
  const today = () => new Date().toISOString().slice(0,10);
  const rows = async (state, table, columns="*") => w.safe(state, table, columns);
  const card = (title, value, note, tone="yellow") => `<article class="ob-op-card ${tone}"><span>${esc(title)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></article>`;
  const status = value => `<span class="ob-status ${String(value||"").toLowerCase()==="paid"||String(value||"").toLowerCase()==="completed" ? "done" : "open"">${esc(value || "Open")}</span>`;
  w.financeView = async state => { const [payments,expenses,accounts]=await Promise.all([rows(state,"payments","id,amount,payment_date,method,reference,created_at"),rows(state,"expenses","id,expense_date,category,description,amount,tax_amount,payment_method,reference,created_at"),rows(state,"payment_accounts","id,name,account_type,opening_balance,current_balance,is_active")]); const received=payments.reduce((s,r)=>s+Number(r.amount||0),0),spent=expenses.reduce((s,r)=>s+Number(r.amount||0),0),balance=accounts.reduce((s,r)=>s+Number(r.current_balance??r.opening_balance??0),0); return `<div class="ob-op-hero"><div><span class="ob-eyebrow">MONEY CONTROL</span><h2>Know where the money is.</h2><p>Track incoming payments, outgoing expenses and payment accounts from one view.</p></div><button class="ob-primary" data-action="new-expense">${w.icon("plus")} Record expense</button></div><section class="ob-op-metrics">${card("Money received",money(received),`${payments.length} recorded payment${payments.length===1?"":"s"}`,"green")}${card("Expenses",money(spent),`${expenses.length} recorded expense${expenses.length===1?"":"s"}`,"pink")}${card("Account balance",money(balance),`${accounts.length} payment account${accounts.length===1?"":"s"}`,"blue")}</section><article class="ob-panel ob-full-panel"><div class="ob-panel-head"><div><span>EXPENSES</span><h3>Recent spending</h3></div><button class="ob-primary small" data-action="new-expense">${w.icon("plus")} Add expense</button></div>${expenses.length?`<div class="ob-table-scroll"><table class="ob-table"><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Method</th><th>Amount</th></tr></thead><tbody>${expenses.slice(0,30).map(r=>`<tr><td>${esc(r.expense_date||"—")}</td><td>${esc(r.category||"General")}</td><td>${esc(r.description||"—")}</td><td>${esc(r.payment_method||"—")}</td><td><strong>${money(r.amount)}</strong></td></tr>`).join("")}</tbody></table></div>`:`<div class="ob-empty"><div>${w.icon("finance")}</div><h4>No expenses recorded</h4><p>Keep operating costs here so reports can reflect real business movement.</p><button class="ob-soft" data-action="new-expense">${w.icon("plus")} Record first expense</button></div>`}</article>`; };
  w.newExpense = state => { const node=w.modal("Record expense",`<form class="ob-form"><div class="ob-form-grid">${w.field("Date","expense_date","date",true,today())}${w.field("Category","category","text",true)}${w.field("Amount","amount","number",true)}${w.field("Tax amount","tax_amount","number",false,"0")}${w.field("Payment method","payment_method")}${w.field("Reference","reference")}</div>${w.textarea("Description","description")}<button class="ob-primary" type="submit">Save expense ${w.icon("arrow")}</button></form>`); node.querySelector("form")?.addEventListener("submit",async e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget).entries()),amount=Number(raw.amount||0),tax=Number(raw.tax_amount||0);if(!raw.category?.trim()||amount<=0||tax<0){w.toast("Enter a valid category and amount");return;}const result=await w.db().from("expenses").insert({business_id:state.businessId,expense_date:raw.expense_date||today(),category:raw.category.trim(),description:raw.description?.trim()||null,amount,tax_amount:tax,payment_method:raw.payment_method?.trim()||null,reference:raw.reference?.trim()||null});if(result.error){w.toast(result.error.message||"Could not save expense");return;}node.remove();w.toast("Expense recorded");await state.renderPage();}); };
  w.purchasesView = async state => { const purchases=await rows(state,"purchases","id,purchase_number,vendor_id,purchase_date,status,subtotal,tax_total,total,notes,created_at"),vendors=await rows(state,"vendors","id,name,company_name"),vm=new Map(vendors.map(v=>[v.id,v.company_name||v.name])),total=purchases.reduce((s,r)=>s+Number(r.total||0),0); return `<div class="ob-op-hero"><div><span class="ob-eyebrow">BUY & STOCK</span><h2>Purchases, connected.</h2><p>Record supplier purchases with real totals and keep buying organised.</p></div><button class="ob-primary" data-action="new-purchase">${w.icon("plus")} New purchase</button></div><article class="ob-panel ob-full-panel"><div class="ob-panel-head"><div><span>PURCHASE REGISTER</span><h3>Supplier purchases</h3></div></div>${purchases.length?`<div class="ob-table-scroll"><table class="ob-table"><thead><tr><th>Purchase</th><th>Supplier</th><th>Date</th><th>Status</th><th>Total</th></tr></thead><tbody>${purchases.map(r=>`<tr><td><strong>${esc(r.purchase_number||"Purchase")}</strong></td><td>${esc(vm.get(r.vendor_id)||"Unknown supplier")}</td><td>${esc(r.purchase_date||"—")}</td><td>${status(r.status)}</td><td><strong>${money(r.total)}</strong></td></tr>`).join("")}</tbody></table></div>`:`<div class="ob-empty"><div>${w.icon("purchases")}</div><h4>No purchases yet</h4><p>Record your first supplier purchase.</p><button class="ob-soft" data-action="new-purchase">${w.icon("plus")} Record purchase</button></div>`}</article>`; };
  w.reportsView = async state => { const [invoices,payments,expenses,purchases,customers,items]=await Promise.all([rows(state,"invoices","id,total,amount_paid,status,issue_date,created_at"),rows(state,"payments","id,amount,payment_date,created_at"),rows(state,"expenses","id,amount,tax_amount,expense_date,category"),rows(state,"purchases","id,total,purchase_date,status"),rows(state,"customers","id,created_at"),rows(state,"items","id,opening_stock,selling_price")]); const sales=invoices.reduce((s,r)=>s+Number(r.total||0),0),received=payments.reduce((s,r)=>s+Number(r.amount||0),0),spent=expenses.reduce((s,r)=>s+Number(r.amount||0),0),bought=purchases.reduce((s,r)=>s+Number(r.total||0),0),outstanding=Math.max(0,sales-invoices.reduce((s,r)=>s+Number(r.amount_paid||0),0)); return `<div class="ob-op-hero"><div><span class="ob-eyebrow">BUSINESS INTELLIGENCE</span><h2>Numbers that explain the business.</h2><p>A live snapshot built from your real records.</p></div></div><section class="ob-op-metrics">${card("Sales",money(sales),`${invoices.length} invoices`,"yellow")}${card("Received",money(received),`${payments.length} payments`,"green")}${card("Outstanding",money(outstanding),"Customer receivables","blue")}${card("Net movement",money(sales-spent-bought),"Sales less purchases and expenses","pink")}</section><section class="ob-op-grid"><article class="ob-panel"><div class="ob-panel-head"><div><span>BUSINESS ACTIVITY</span><h3>Records</h3></div></div><div class="ob-op-list"><div><span>Customers</span><strong>${customers.length}</strong></div><div><span>Catalogue items</span><strong>${items.length}</strong></div><div><span>Purchases</span><strong>${purchases.length}</strong></div><div><span>Invoices</span><strong>${invoices.length}</strong></div></div></article></section>`; };
  w.pageView = async (page,state) => { if(page==="finance") return w.financeView(state); if(page==="purchases") return w.purchasesView(state); if(page==="reports") return w.reportsView(state); return null; };
})();
