/* OrbitBiz workspace — quotations, conversion and supplier directory. */
(() => {
  "use strict";
  const core = window.OrbitBiz = window.OrbitBiz || {};
  const w = core.workspace = core.workspace || {};
  const esc = v => w.esc(v);
  const money = v => w.money(v);
  const today = () => new Date().toISOString().slice(0,10);
  const rows = (state, table, columns="*") => w.safe(state, table, columns);
  const status = value => { const v=String(value||"draft"); return `<span class="ob-status ${["accepted","converted","paid"].includes(v)?"done":"open"}">${esc(v.replace(/_/g," "))}</span>`; };

  w.quotationsView = async state => {
    const [quotes, customers] = await Promise.all([rows(state,"quotations","id,customer_id,quote_number,status,issue_date,expiry_date,subtotal,discount_total,tax_total,total,notes,created_at"), rows(state,"customers","id,name,company_name")]);
    const cm = new Map(customers.map(c=>[c.id,c.company_name||c.name]));
    const value = quotes.reduce((s,q)=>s+Number(q.total||0),0);
    return `<div class="ob-op-hero ob-sales-hero"><div><span class="ob-eyebrow">SALES FLOW</span><h2>Quote the work. Win the sale.</h2><p>Create customer quotations, track their state and turn an accepted quote into a real invoice.</p></div><button class="ob-primary" data-action="new-quotation">${w.icon("plus")} New quotation</button></div><section class="ob-op-metrics"><article class="ob-op-card yellow"><span>Quoted value</span><strong>${money(value)}</strong><small>${quotes.length} quotation${quotes.length===1?"":"s"}</small></article><article class="ob-op-card blue"><span>Customers</span><strong>${customers.length}</strong><small>Available for quoting</small></article><article class="ob-op-card green"><span>Accepted</span><strong>${quotes.filter(q=>["accepted","converted"].includes(String(q.status||"").toLowerCase())).length}</strong><small>Ready for fulfilment</small></article></section><article class="ob-panel ob-full-panel"><div class="ob-panel-head"><div><span>QUOTE REGISTER</span><h3>Customer quotations</h3></div><button class="ob-primary small" data-action="new-quotation">${w.icon("plus")} Add quotation</button></div>${quotes.length?`<div class="ob-table-scroll"><table class="ob-table"><thead><tr><th>Quote</th><th>Customer</th><th>Issue</th><th>Expiry</th><th>Status</th><th>Total</th><th></th></tr></thead><tbody>${quotes.map(q=>`<tr><td><strong>${esc(q.quote_number||"Quote")}</strong></td><td>${esc(cm.get(q.customer_id)||"No customer")}</td><td>${esc(q.issue_date||"—")}</td><td>${esc(q.expiry_date||"—")}</td><td>${status(q.status)}</td><td><strong>${money(q.total)}</strong></td><td>${["accepted","converted"].includes(String(q.status||"").toLowerCase())&&q.status!=="converted"?`<button class="ob-row-action" data-action="convert-quotation" data-id="${esc(q.id)}">Convert</button>`:`<button class="ob-row-action" data-action="accept-quotation" data-id="${esc(q.id)}">${String(q.status||"").toLowerCase()==="converted"?"Converted":"Accept"}</button>`}</td></tr>`).join("")}</tbody></table></div>`:`<div class="ob-empty"><div>${w.icon("quotations")}</div><h4>No quotations yet</h4><p>Build your first quote and connect it directly to invoicing.</p><button class="ob-soft" data-action="new-quotation">${w.icon("plus")} Create first quote</button></div>`}</article>`;
  };

  w.newQuotation = async state => {
    const [customers,items]=await Promise.all([rows(state,"customers","id,name,company_name"),rows(state,"items","id,name,sku,selling_price,tax_rate")]);
    const line=()=>`<div class="ob-purchase-line ob-quote-line" data-quote-line><select data-item><option value="">Select item</option>${items.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}${x.sku?` · ${esc(x.sku)}`:""}</option>`).join("")}</select><input data-description placeholder="Description" required><input data-qty type="number" min="0.001" step="0.001" value="1"><input data-price type="number" min="0" step="0.01" value="0"><input data-discount type="number" min="0" step="0.01" value="0"><input data-tax type="number" min="0" step="0.01" value="0"><strong data-total>₹0</strong><button type="button" data-remove-line>×</button></div>`;
    const node=w.modal("New quotation",`<form class="ob-form ob-purchase-form"><div class="ob-form-grid"><label class="ob-field"><span>Customer</span><select name="customer_id" required><option value="">Select customer</option>${customers.map(c=>`<option value="${esc(c.id)}">${esc(c.company_name||c.name)}</option>`).join("")}</select></label>${w.field("Issue date","issue_date","date",true,today())}${w.field("Expiry date","expiry_date","date",false)}</div><div class="ob-invoice-lines-wrap"><div class="ob-invoice-lines-head"><span>LINE ITEMS</span><button type="button" class="ob-soft" data-add-quote-line>${w.icon("plus")} Add line</button></div><div class="ob-quote-line labels"><span>Item</span><span>Description</span><span>Qty</span><span>Rate</span><span>Disc.</span><span>Tax %</span><span>Total</span><span></span></div><div data-quote-lines>${line()}</div></div>${w.textarea("Notes","notes","","Optional quote notes")}<div class="ob-purchase-summary"><span>Total</span><strong data-quote-grand>₹0</strong></div><button class="ob-primary" type="submit">Save quotation ${w.icon("arrow")}</button></form>`);
    const form=node.querySelector("form"), container=node.querySelector("[data-quote-lines]");
    const recalc=()=>{let grand=0;container.querySelectorAll("[data-quote-line]").forEach(r=>{const q=Math.max(0,Number(r.querySelector("[data-qty]").value||0)),p=Math.max(0,Number(r.querySelector("[data-price]").value||0)),d=Math.min(100,Math.max(0,Number(r.querySelector("[data-discount]").value||0))),t=Math.max(0,Number(r.querySelector("[data-tax]").value||0)),base=q*p*(1-d/100),total=base*(1+t/100);grand+=total;r.querySelector("[data-total]").textContent=money(total);});node.querySelector("[data-quote-grand]").textContent=money(grand);};
    const bind=row=>{row.querySelector("[data-item]").addEventListener("change",e=>{const x=items.find(i=>i.id===e.target.value);if(x){row.querySelector("[data-description]").value=x.name;row.querySelector("[data-price]").value=Number(x.selling_price||0);row.querySelector("[data-tax]").value=Number(x.tax_rate||0);recalc();}});row.querySelectorAll("input").forEach(i=>i.addEventListener("input",recalc));row.querySelector("[data-remove-line]").addEventListener("click",()=>{if(container.children.length>1){row.remove();recalc();}else w.toast("A quotation needs at least one line");});};
    bind(container.firstElementChild);node.querySelector("[data-add-quote-line]").addEventListener("click",()=>{container.insertAdjacentHTML("beforeend",line());bind(container.lastElementChild);recalc();});
    form.addEventListener("submit",async e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(form).entries());const lines=[...container.querySelectorAll("[data-quote-line]")].map(r=>({item_id:r.querySelector("[data-item]").value||null,description:r.querySelector("[data-description]").value.trim(),quantity:Number(r.querySelector("[data-qty]").value||0),unit_price:Number(r.querySelector("[data-price]").value||0),discount:Number(r.querySelector("[data-discount]").value||0),tax_rate:Number(r.querySelector("[data-tax]").value||0)}));if(!raw.customer_id||lines.some(x=>!x.description||x.quantity<=0||x.unit_price<0||x.discount<0||x.tax_rate<0)){w.toast("Complete the customer and quote lines");return;}const subtotal=lines.reduce((s,x)=>s+x.quantity*x.unit_price,0),discount_total=lines.reduce((s,x)=>s+x.quantity*x.unit_price*x.discount/100,0),tax_total=lines.reduce((s,x)=>s+(x.quantity*x.unit_price-x.quantity*x.unit_price*x.discount/100)*x.tax_rate/100,0),total=subtotal-discount_total+tax_total;const quoteNumber=`QUO-${Date.now().toString().slice(-8)}`;const qr=await w.db().from("quotations").insert({business_id:state.businessId,customer_id:raw.customer_id,quote_number:quoteNumber,status:"draft",issue_date:raw.issue_date||today(),expiry_date:raw.expiry_date||null,subtotal,discount_total,tax_total,total,notes:raw.notes?.trim()||null}).select("id").single();if(qr.error){w.toast(qr.error.message||"Could not save quotation");return;}const ir=await w.db().from("quotation_items").insert(lines.map(x=>({...x,quotation_id:qr.data.id,line_total:(x.quantity*x.unit_price-x.quantity*x.unit_price*x.discount/100)*(1+x.tax_rate/100)})));if(ir.error){w.toast(ir.error.message||"Quotation saved but lines failed");return;}node.remove();w.toast("Quotation saved");await state.renderPage();});recalc();
  };

  w.acceptQuotation=async(state,id)=>{const r=await w.db().from("quotations").update({status:"accepted"}).eq("id",id).eq("business_id",state.businessId);if(r.error){w.toast(r.error.message||"Could not accept quotation");return;}w.toast("Quotation accepted");await state.renderPage();};
  w.convertQuotation=async(state,id)=>{const client=w.db();const q=await client.from("quotations").select("id,business_id,customer_id,quote_number,subtotal,discount_total,tax_total,total,notes").eq("id",id).eq("business_id",state.businessId).maybeSingle();if(q.error||!q.data){w.toast("Quotation could not be loaded");return;}const existing=await client.from("invoices").select("id").eq("business_id",state.businessId).eq("invoice_number",`INV-${q.data.quote_number.replace(/^QUO-/i,"")}`).maybeSingle();if(existing.data?.id){w.toast("Invoice already exists for this quotation");return;}const invoiceNumber=`INV-${Date.now().toString().slice(-8)}`;const inv=await client.from("invoices").insert({business_id:state.businessId,customer_id:q.data.customer_id,invoice_number:invoiceNumber,status:"draft",issue_date:today(),subtotal:q.data.subtotal||0,discount_total:q.data.discount_total||0,tax_total:q.data.tax_total||0,total:q.data.total||0,amount_paid:0,notes:q.data.notes||null}).select("id").single();if(inv.error){w.toast(inv.error.message||"Could not create invoice");return;}const lines=await client.from("quotation_items").select("item_id,description,quantity,unit_price,discount,tax_rate,line_total").eq("quotation_id",id);if(lines.error){w.toast("Invoice created, but quote lines could not be copied");return;}const copy=await client.from("invoice_items").insert((lines.data||[]).map((x,i)=>({...x,invoice_id:inv.data.id,sort_order:i})));if(copy.error){w.toast(copy.error.message||"Invoice created, but line copy failed");return;}const upd=await client.from("quotations").update({status:"converted"}).eq("id",id).eq("business_id",state.businessId);if(upd.error){w.toast("Invoice created; quotation status could not be updated");return;}w.toast(`Invoice ${invoiceNumber} created`);state.openInvoice(inv.data.id);};

  w.vendorsView=async state=>{const vendors=await rows(state,"vendors","id,name,company_name,email,phone,gstin,opening_balance,is_active,created_at");return `<div class="ob-op-hero"><div><span class="ob-eyebrow">SUPPLIER DIRECTORY</span><h2>Know who you buy from.</h2><p>Keep supplier contacts, tax details and opening balances ready for purchasing.</p></div><button class="ob-primary" data-action="new-vendor">${w.icon("plus")} New supplier</button></div><article class="ob-panel ob-full-panel"><div class="ob-panel-head"><div><span>SUPPLIERS</span><h3>${vendors.length} vendor${vendors.length===1?"":"s"}</h3></div><button class="ob-primary small" data-action="new-vendor">${w.icon("plus")} Add supplier</button></div>${vendors.length?`<div class="ob-table-scroll"><table class="ob-table"><thead><tr><th>Supplier</th><th>Contact</th><th>GSTIN</th><th>Opening balance</th><th>Status</th><th></th></tr></thead><tbody>${vendors.map(v=>`<tr><td><div class="ob-table-person"><div class="ob-list-avatar tone-blue">${esc(String(v.name||"?").charAt(0).toUpperCase())}</div><div><strong>${esc(v.company_name||v.name)}</strong><small>${esc(v.company_name?v.name:"Supplier")}</small></div></div></td><td><div class="ob-table-contact"><span>${esc(v.phone||"No phone")}</span><span>${esc(v.email||"No email")}</span></div></td><td>${esc(v.gstin||"—")}</td><td>${money(v.opening_balance)}</td><td>${v.is_active===false?`<span class="ob-status open">Inactive</span>`:`<span class="ob-status done">Active</span>`}</td><td><button class="ob-row-action" data-action="edit-vendor" data-id="${esc(v.id)}">Edit</button></td></tr>`).join("")}</tbody></table></div>`:`<div class="ob-empty"><div>${w.icon("purchases")}</div><h4>No suppliers yet</h4><p>Add suppliers before recording purchases.</p><button class="ob-soft" data-action="new-vendor">${w.icon("plus")} Add first supplier</button></div>`}</article>`;};

  w.vendorForm=(state,vendor=null)=>{const editing=Boolean(vendor?.id);const node=w.modal(editing?"Edit supplier":"Add supplier",`<form class="ob-form"><div class="ob-form-grid">${w.field("Name","name","text",true,vendor?.name)}${w.field("Company","company_name","text",false,vendor?.company_name)}${w.field("Phone","phone","tel",false,vendor?.phone)}${w.field("Email","email","email",false,vendor?.email)}${w.field("GSTIN","gstin","text",false,vendor?.gstin)}${w.field("Opening balance","opening_balance","number",false,vendor?.opening_balance)}</div>${w.textarea("Notes","notes",vendor?.notes,"Optional supplier notes")}<button class="ob-primary" type="submit">${editing?"Save changes":"Save supplier"} ${w.icon("arrow")}</button></form>`);node.querySelector("form").addEventListener("submit",async e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget).entries());const data={name:String(raw.name||"").trim(),company_name:String(raw.company_name||"").trim()||null,phone:String(raw.phone||"").trim()||null,email:String(raw.email||"").trim()||null,gstin:String(raw.gstin||"").trim()||null,opening_balance:Number(raw.opening_balance||0),notes:String(raw.notes||"").trim()||null};if(!data.name||!Number.isFinite(data.opening_balance)){w.toast("Enter a valid supplier name and balance");return;}const r=editing?await w.db().from("vendors").update(data).eq("id",vendor.id).eq("business_id",state.businessId):await w.db().from("vendors").insert({...data,business_id:state.businessId});if(r.error){w.toast(r.error.message||"Could not save supplier");return;}node.remove();w.toast(editing?"Supplier updated":"Supplier added");await state.renderPage();});};
  w.newVendor=state=>w.vendorForm(state);
  w.editVendor=async(state,id)=>{const vendor=(await rows(state,"vendors")).find(v=>v.id===id);if(vendor)w.vendorForm(state,vendor);else w.toast("Supplier could not be found");};
  const previous=w.pageView;
  w.pageView=async(page,state)=>{if(page==="quotations")return w.quotationsView(state);if(page==="vendors")return w.vendorsView(state);return typeof previous==="function"?previous(page,state):null;};
})();
