/* OrbitBiz workspace — business profile and workspace settings. */
(() => {
  "use strict";
  const core=window.OrbitBiz=window.OrbitBiz||{}; const w=core.workspace=core.workspace||{};
  const esc=v=>w.esc(v); const today=()=>new Date().toISOString().slice(0,10);
  const load=async state=>{const r=await w.db().from("businesses").select("*").eq("id",state.businessId).maybeSingle();if(r.error)throw r.error;return r.data||{id:state.businessId};};
  const field=(label,name,type,value,placeholder="")=>`<label class="ob-field"><span>${esc(label)}</span><input name="${esc(name)}" type="${type}" value="${esc(value??"")}" placeholder="${esc(placeholder)}"></label>`;
  w.settingsView=async state=>{const b=await load(state);return `<div class="ob-op-hero ob-settings-hero"><div><span class="ob-eyebrow">WORKSPACE SETTINGS</span><h2>Make OrbitBiz yours.</h2><p>Keep your business identity and tax details ready for invoices, reports and future documents.</p></div></div><form class="ob-panel ob-settings-form" data-settings-form><div class="ob-panel-head"><div><span>BUSINESS PROFILE</span><h3>Identity</h3></div><span class="ob-settings-badge">${w.icon("settings")} Private workspace</span></div><div class="ob-form-grid">${field("Business name","name","text",b.name,"Your business name")}${field("Legal / company name","legal_name","text",b.legal_name,"Optional legal name")}${field("Email","email","email",b.email,"Business email")}${field("Phone","phone","tel",b.phone,"Business phone")}${field("GSTIN","gstin","text",b.gstin,"Optional GSTIN")}${field("PAN","pan","text",b.pan,"Optional PAN")}${field("Website","website","url",b.website,"https://")}${field("Currency","currency","text",b.currency||"INR","INR")}</div>${w.textarea("Business address","address",b.address||"","Address shown on business documents")}<div class="ob-settings-divider"></div><div class="ob-panel-head compact"><div><span>WORKSPACE</span><h3>Defaults</h3></div></div><div class="ob-form-grid">${field("Financial year starts","financial_year_start","date",b.financial_year_start||`${new Date().getFullYear()}-04-01`)}${field("Timezone","timezone","text",b.timezone||"Asia/Kolkata","Asia/Kolkata")}</div><div class="ob-settings-actions"><span>Changes apply to this business workspace.</span><button class="ob-primary" type="submit">Save changes ${w.icon("arrow")}</button></div></form>`};
  w.saveSettings=async(e,state)=>{e.preventDefault();const form=e.currentTarget;const raw=Object.fromEntries(new FormData(form).entries());if(!raw.name?.trim()){w.toast("Business name is required");return;}const payload={name:raw.name.trim(),legal_name:raw.legal_name?.trim()||null,email:raw.email?.trim()||null,phone:raw.phone?.trim()||null,gstin:raw.gstin?.trim()||null,pan:raw.pan?.trim()||null,website:raw.website?.trim()||null,currency:raw.currency?.trim()||"INR",address:raw.address?.trim()||null,financial_year_start:raw.financial_year_start||null,timezone:raw.timezone?.trim()||"Asia/Kolkata"};const r=await w.db().from("businesses").update(payload).eq("id",state.businessId);if(r.error){w.toast(r.error.message||"Could not save settings");return;}w.toast("Business profile saved");await state.renderPage();};
  w.pageView=async(page,state)=>{if(page==="settings")return w.settingsView(state);if(page==="vendors")return w.vendorsView(state);if(page==="quotations")return w.quotationsView(state);if(page==="finance")return w.financeView(state);if(page==="purchases")return w.purchasesView(state);if(page==="reports")return w.reportsView(state);return null;};
  document.addEventListener("submit",e=>{if(e.target.matches("[data-settings-form]")){const state=core.workspaceState;if(state)w.saveSettings(e,state);}});
})();